<?php

require 'vendor/autoload.php';
require 'helpers.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;


if (!isset($argv)) { $argv = []; }
if (count($argv) < 2) {
	echo "Usage: php to-html.php [files]\n";
	exit();
}

for ($a = 1; $a < count($argv); $a++) {
	$inputFile = $argv[$a];

	$fileInfo = pathinfo($inputFile);
	echo "Reading file: " . $inputFile . "\n";

	$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader('Xlsx');
	$reader->setReadDataOnly(TRUE);
	$spreadsheet = $reader->load($inputFile);
	$sheet = $spreadsheet->getActiveSheet();

	$out = [];
	$row = 2;
	while (true) {
		if (!($line = $sheet->getCellByColumnAndRow(1, $row)->getValue())) {
			break;
		}
		$internal = $sheet->getCellByColumnAndRow(2, $row)->getValue();

//			echo $row . ": " . $line . "\n";
		$out[$internal] = [
			'line' => $line,
			'pre' => $sheet->getCellByColumnAndRow(3, $row)->getValue(),
			'post' => $sheet->getCellByColumnAndRow(4, $row)->getValue(),
			'master' => $sheet->getCellByColumnAndRow(5, $row)->getValue(),
			'translation' => $sheet->getCellByColumnAndRow(6, $row)->getValue(),
		];

		$row++;
	}


	// Output html
	$outFile = $fileInfo['dirname'] . "/" . $fileInfo['filename'] . "-translated.html";
	echo "Writing file: " . $outFile . "\n";

	ksort($out);
	$file = fopen($outFile, "w");
	fwrite($file, "#
#
# Editing guidelines:
# 1. Edit this file with a text editor like Notepad++ http://notepad-plus-plus.org/
#    - notepad++ with language set to HTML will show translation text inside HTML as black
# 2. DO NOT edit this file with MS Word, Wordpad, or a HTML WYSIWYG editor it may corrupt the format
# 3. Save the file with UTF-8 encoding ( without BOM if you have the option ).
# 4. Keep the end of line (line feed) character, ensure your editor inserts the same.
#
#
");
	$lastLine = '';
	foreach ($out as $info) {
		if ($lastLine != $info['line']) {
			fwrite($file, "\n##~~Do not edit this line." . $info['line'] . "~~##\n");
			$lastLine = $info['line'];
		}
		fwrite($file, $info['pre'] . ($info['translation']) . $info['post']);
	}
	fclose($file);

}


